## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("CSEB_Attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0%,Critical,36 more,Never,12
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
print("First 10 rows:")
display(df.head(10))

print("Shape:", df.shape)

print("Data types:")
print(df.dtypes)

First 10 rows:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
5,4MW24CS066,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,8%,Critical,32 more,2026-09-18,5
6,4MW24CS067,KRITHI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
7,4MW24CS068,KRITHIKA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
8,4MW24CS069,LAKSHMI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
9,4MW24CS070,LAVANYA SHANKAR MOGER,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0

Shape: (65, 12)
Data types:
Roll No                 object
Student Name            object
Subject                 object
Total Classes            int64
Present                  int64
Absent                   int64
Excused                  int64
Attendance %            object
Status                  object
Classes Needed (75%)    object
Last Present Date       object
Consecutive Absences     int64
dtype: object

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
print("Missing values:")
print(df.isnull().sum())

print("Number of Never dates:")
print(
    df["Last Present Date"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("never")
    .sum()
)

Missing values:
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64
Number of Never dates:
2

In [5]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
def to_snake_case(column):
    return (
        column.strip()
        .lower()
        .replace("%", "pct")
        .replace("(", "")
        .replace(")", "")
        .replace(" ", "_")
        .replace("-", "_")
    )

df.columns = [to_snake_case(col) for col in df.columns]

print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences']

In [6]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_pct"] = (
    df["attendance_pct"]
    .astype(str)
    .str.rstrip("%")
    .astype(float)
)

df["last_present_date"] = pd.to_datetime(
    df["last_present_date"].replace("Never", pd.NA),
    errors="coerce"
)

print(df[["attendance_pct", "last_present_date"]].dtypes)

attendance_pct              float64
last_present_date    datetime64[ns]
dtype: object

#### Section 2: Filtering & Selection

In [7]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
critical_students = df[
    df["status"].str.strip().str.lower() == "critical"
].sort_values(by="attendance_pct")

display(critical_students)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
10,4MW24CS071,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.0,Critical,36 more,NaT,12
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.0,Critical,36 more,NaT,12
13,4MW24CS074,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,8.0,Critical,32 more,2026-09-22,4
5,4MW24CS066,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,8.0,Critical,32 more,2026-09-18,5
49,4MW24CS110,PRATHWEESH,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,8.0,Critical,32 more,2026-09-18,5
46,4MW24CS107,PRATHAM G KUMAR,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,8.0,Critical,32 more,2026-09-18,5
35,4MW24CS096,NITHIL SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,8.0,Critical,32 more,2026-09-18,5
29,4MW24CS090,NIKHIL NAIK,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,58.0,Critical,8 more,2026-10-09,0
51,4MW24CS112,RAHUL,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,58.0,Critical,8 more,2026-09-29,2

In [8]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
fully_absent = df.loc[
    df["present"] == 0,
    ["roll_no", "student_name", "consecutive_absences"]
]

display(fully_absent)

       roll_no     student_name  consecutive_absences
10  4MW24CS071       LAXMEESH V                    12
63  4MW25CS405  MANYA PRARTHANA                    12

In [9]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
# Safe students using loc
safe_students = df.loc[
    df["status"].str.strip().str.lower() == "safe"
]

display(safe_students)

# First 15 rows and columns 2 to 6 using iloc
display(df.iloc[:15, 1:6])

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
6,4MW24CS067,KRITHI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
7,4MW24CS068,KRITHIKA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
8,4MW24CS069,LAKSHMI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
11,4MW24CS072,LIKHITA S,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
12,4MW24CS073,LIPIKA NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
14,4MW24CS075,MANASA R KULAL,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
15,4MW24CS076,MANOJ KUMAR,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
16,4MW24CS077,MANYA,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
17,4MW24CS078,MANYA B C,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
19,4MW24CS080,MAYUR S KULAL,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
20,4MW24CS081,MEGHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
22,4MW24CS083,MOKSHA JEETENDRA MURUDESHWARA,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
23,4MW24CS084,NANDAN NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
24,4MW24CS085,NARMADA S,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
26,4MW24CS087,NAVYA NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
27,4MW24CS088,NEHA(VIJAYA POOJARY),Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
31,4MW24CS092,NIRMITHA K NAGARAJ,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
32,4MW24CS093,NISHA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
34,4MW24CS095,NISHMITHA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
36,4MW24CS097,PANCHAMI NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
37,4MW24CS098,PANCHAMI V DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
38,4MW24CS099,POOJASHREE,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
39,4MW24CS100,POORVI SUNIL DEV,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
40,4MW24CS101,POORVIKA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
41,4MW24CS102,PRAJNA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
43,4MW24CS104,PRANATHI S KONI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
45,4MW24CS106,PRANAV P K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
47,4MW24CS108,PRATHIKA P SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
48,4MW24CS109,PRATHIKSHA P SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
52,4MW24CS113,RAJIYA BEGAM SURKOD,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
54,4MW24CS115,RAMYA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
56,4MW24CS117,ROHAN MENDON,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
57,4MW24CS118,SAFA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
58,4MW24CS119,SAGAR H POOJARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
59,4MW24CS120,SAHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0

,student_name,subject,total_classes,present,absent
0,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
1,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
2,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
3,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1
4,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1
5,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11
6,KRITHI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
7,KRITHIKA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
8,LAKSHMI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
9,LAVANYA SHANKAR MOGER,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2
10,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12
11,LIKHITA S,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
12,LIPIKA NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1
13,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11
14,MANASA R KULAL,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0

In [10]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
students_absent = df.loc[
    df["consecutive_absences"] >= 5,
    ["student_name", "status", "last_present_date"]
]

display(students_absent)

       student_name    status last_present_date
5        KOUSHTUBHA  Critical        2026-09-18
10       LAXMEESH V  Critical               NaT
35    NITHIL SHETTY  Critical        2026-09-18
46  PRATHAM G KUMAR  Critical        2026-09-18
49       PRATHWEESH  Critical        2026-09-18
63  MANYA PRARTHANA  Critical               NaT

### Section 3: Grouping & Aggregation

In [11]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
status_summary = df.groupby("status", dropna=False).agg(
    student_count=("roll_no", "count"),
    average_attendance_pct=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
).reset_index()

display(status_summary)

     status  student_count  average_attendance_pct  max_consecutive_absences
0  Critical              9               17.333333                        12
1      Safe             42               96.952381                         0
2   Warning             14               80.714286                         1

In [12]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_category"] = np.select(
    [
        df["attendance_pct"] >= 90,
        df["attendance_pct"] >= 75,
        df["attendance_pct"] >= 60
    ],
    [
        "Excellent",
        "Good",
        "Average"
    ],
    default="Poor"
)

print(df["attendance_category"].value_counts())

attendance_category
Excellent    42
Good         14
Poor          9
Name: count, dtype: int64

In [13]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
totals = df.agg({
    "total_classes": "sum",
    "present": "sum",
    "absent": "sum"
})

print("Total classes:", totals["total_classes"])
print("Total present:", totals["present"])
print("Total absent:", totals["absent"])

Total classes: 780
Total present: 643
Total absent: 137

In [14]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
status_attendance = df.groupby("status").agg(
    present_min=("present", "min"),
    present_max=("present", "max"),
    present_mean=("present", "mean"),
    absent_sum=("absent", "sum")
)

display(status_attendance)

          present_min  present_max  present_mean  absent_sum
status
Critical            0            7      2.111111          89
Safe               11           12     11.619048          16
Warning             9           10      9.714286          32

### Section 4: Feature Engineering & Transformation

In [15]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df["risk_score"] = (
    df["absent"] * 0.4
    + df["consecutive_absences"] * 0.6
)

top_10_risk = df.nlargest(10, "risk_score")

display(
    top_10_risk[
        ["roll_no", "student_name", "absent",
         "consecutive_absences", "risk_score"]
    ]
)

       roll_no     student_name  absent  consecutive_absences  risk_score
10  4MW24CS071       LAXMEESH V      12                    12        12.0
63  4MW25CS405  MANYA PRARTHANA      12                    12        12.0
5   4MW24CS066       KOUSHTUBHA      11                     5         7.4
35  4MW24CS096    NITHIL SHETTY      11                     5         7.4
46  4MW24CS107  PRATHAM G KUMAR      11                     5         7.4
49  4MW24CS110       PRATHWEESH      11                     5         7.4
13  4MW24CS074   MAHALINGAPPA C      11                     4         6.8
51  4MW24CS112            RAHUL       5                     2         3.2
29  4MW24CS090      NIKHIL NAIK       5                     0         2.0
33  4MW24CS094        NISHA M B       2                     1         1.4

In [16]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
df["classes_needed_numeric"] = (
    df["classes_needed_75pct"]
    .astype(str)
    .str.extract(r"(\d+)", expand=False)
    .fillna("0")
    .astype(int)
)

display(
    df[["classes_needed_75pct", "classes_needed_numeric"]].head(10)
)

  classes_needed_75pct  classes_needed_numeric
0                ✓ Met                       0
1                ✓ Met                       0
2                ✓ Met                       0
3                ✓ Met                       0
4                ✓ Met                       0
5              32 more                      32
6                ✓ Met                       0
7                ✓ Met                       0
8                ✓ Met                       0
9                ✓ Met                       0

In [17]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df["attendance_flag"] = df["attendance_pct"].apply(
    lambda x: "Defaulter" if x < 75 else "Safe"
)

display(df[["student_name", "attendance_pct", "attendance_flag"]])

         student_name  attendance_pct attendance_flag
0        KAVYA KAMATH           100.0            Safe
1           KEERTHANA           100.0            Safe
2    KEERTHI.R.SHETTY           100.0            Safe
3              KHUSHI            92.0            Safe
4      KISHAN KUMAR K            92.0            Safe
..                ...             ...             ...
60           SAHANA M            83.0            Safe
61             SAKSHI            92.0            Safe
62  MANISH M BHANDARY            92.0            Safe
63    MANYA PRARTHANA             0.0       Defaulter
64              ROHAN            83.0            Safe

[65 rows x 3 columns]

In [18]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_range"] = pd.cut(
    df["attendance_pct"],
    bins=[0, 50, 75, 90, 100],
    labels=["Critical", "Warning", "Good", "Excellent"],
    include_lowest=True
)

display(df[["student_name", "attendance_pct", "attendance_range"]])

         student_name  attendance_pct attendance_range
0        KAVYA KAMATH           100.0        Excellent
1           KEERTHANA           100.0        Excellent
2    KEERTHI.R.SHETTY           100.0        Excellent
3              KHUSHI            92.0        Excellent
4      KISHAN KUMAR K            92.0        Excellent
..                ...             ...              ...
60           SAHANA M            83.0             Good
61             SAKSHI            92.0        Excellent
62  MANISH M BHANDARY            92.0        Excellent
63    MANYA PRARTHANA             0.0         Critical
64              ROHAN            83.0             Good

[65 rows x 3 columns]

### Section 5: Advanced Analysis

In [19]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
pivot_summary = pd.pivot_table(
    df,
    index="status",
    columns="attendance_category",
    values="roll_no",
    aggfunc="count",
    fill_value=0,
    observed=False
)

display(pivot_summary)

attendance_category  Excellent  Good  Poor
status
Critical                     0     0     9
Safe                        42     0     0
Warning                      0    14     0

In [20]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
df["base_name"] = (
    df["student_name"]
    .astype(str)
    .str.strip()
    .str.split()
    .str[0]
    .str.upper()
)

duplicate_bases = df[
    df.duplicated(subset="base_name", keep=False)
].sort_values("base_name")

print("Repeated base names:")
print(duplicate_bases["base_name"].value_counts())

display(duplicate_bases)

Repeated base names:
base_name
MANYA       3
NAVYA       2
NISHA       2
PANCHAMI    2
PRANAV      2
ROHAN       2
SAHANA      2
Name: count, dtype: int64

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
16,4MW24CS077,MANYA,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,MANYA
17,4MW24CS078,MANYA B C,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,MANYA
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,Critical,MANYA
25,4MW24CS086,NAVYA,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,0,Good,0.8,0,Safe,Good,NAVYA
26,4MW24CS087,NAVYA NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,NAVYA
32,4MW24CS093,NISHA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,NISHA
33,4MW24CS094,NISHA M B,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83.0,Warning,✓ Met,2026-10-06,1,Good,1.4,0,Safe,Good,NISHA
36,4MW24CS097,PANCHAMI NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,PANCHAMI
37,4MW24CS098,PANCHAMI V DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,PANCHAMI
44,4MW24CS105,PRANAV,Data Science & GenAI - 3nd Yr - CSE - B,12,9,3,0,75.0,Warning,✓ Met,2026-10-09,0,Good,1.2,0,Safe,Warning,PRANAV
45,4MW24CS106,PRANAV P K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,PRANAV
56,4MW24CS117,ROHAN MENDON,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,ROHAN
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,0,Good,0.8,0,Safe,Good,ROHAN
59,4MW24CS120,SAHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,SAHANA
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,0,Good,0.8,0,Safe,Good,SAHANA

In [21]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
student_details = df[["roll_no"]].drop_duplicates().copy()

student_details["branch"] = "CSE"
student_details["semester"] = 5

merged_df = pd.merge(
    df,
    student_details,
    on="roll_no",
    how="inner"
)

display(merged_df)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name,branch,semester
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,KAVYA,CSE,5
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,KEERTHANA,CSE,5
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,KEERTHI.R.SHETTY,CSE,5
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,KHUSHI,CSE,5
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,KISHAN,CSE,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,0,Good,0.8,0,Safe,Good,SAHANA,CSE,5
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,SAKSHI,CSE,5
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,MANISH,CSE,5
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,Critical,MANYA,CSE,5
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,0,Good,0.8,0,Safe,Good,ROHAN,CSE,5

In [22]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------
critical_students.to_csv("critical_students.csv", index=False)

status_summary.to_csv("status_summary.csv", index=False)

top_10_risk.to_csv("top_10_risk_students.csv", index=False)

print("All CSV files exported successfully!")

All CSV files exported successfully!